# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d7217a8492a28fd22c4d12e124452883b159767cc409dfbdf293c8eac09aafa835aba113e34df94a4a11a4ecb301932c7f8158696f218047dc7da76a8fa097

test:
  secret_key_base: 53e5564a2237992284b9d74a2c2bcfd9188a9046127af65e652f5a6d50489e1cccd4febd99e14740c4dde987527051118167dc82c1d777f0bf8a90285846dbd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
